class Timetable < ActiveRecord::Base
    serialize :mon_time_09
    serialize  :mon_time_10
    serialize  :mon_time_11
    serialize  :mon_time_12
    serialize  :mon_time_13
    serialize  :mon_time_14
    serialize  :mon_time_15
    serialize  :mon_time_16
    serialize  :mon_time_17
    serialize  :mon_time_18
    serialize  :mon_time_19
    serialize  :tue_time_09
    serialize  :tue_time_10
    serialize  :tue_time_11
    serialize  :tue_time_12
    serialize  :tue_time_13
    serialize  :tue_time_14
    serialize  :tue_time_15
    serialize  :tue_time_16
    serialize  :tue_time_17
    serialize  :tue_time_18
    serialize  :tue_time_19
    serialize  :wed_time_09
    serialize  :wed_time_10
    serialize  :wed_time_11
    serialize  :wed_time_12
    serialize  :wed_time_13
    serialize  :wed_time_14
    serialize  :wed_time_15
    serialize  :wed_time_16
    serialize  :wed_time_17
    serialize  :wed_time_18
    serialize  :wed_time_19
    serialize  :thu_time_09
    serialize  :thu_time_10
    serialize  :thu_time_11
    serialize  :thu_time_12
    serialize  :thu_time_13
    serialize  :thu_time_14
    serialize  :thu_time_15
    serialize  :thu_time_16
    serialize  :thu_time_17
    serialize  :thu_time_18
    serialize  :thu_time_19
    serialize  :fri_time_09
    serialize  :fri_time_10
    serialize  :fri_time_11
    serialize  :fri_time_12
    serialize  :fri_time_13
    serialize  :fri_time_14
    serialize  :fri_time_15
    serialize  :fri_time_16
    serialize  :fri_time_17
    serialize  :fri_time_18
    serialize  :fri_time_19
end
